"""Automated verification harness for AI-assisted coding outputs.

Validates that code generated by AI coding assistants (Claude Code, Cursor, Copilot)
meets production engineering standards:
1. No hardcoded credentials or API tokens
2. No dangerous unbounded memory or ReDoS patterns
3. Type annotations present on public interfaces
4. Deterministic error handling instead of broad except passes
"""
from __future__ import annotations

import ast
import re
from typing import Dict, List


class AICodeAuditor:
    """Static and semantic linter for AI assistant generated code."""

    FORBIDDEN_PATTERNS = [
        (re.compile(r"sk-[a-zA-Z0-9]{20,}"), "Hardcoded OpenAI secret key detected!"),
        (re.compile(r"AKIA[0-9A-Z]{16}"), "Hardcoded AWS Access Key detected!"),
        (re.compile(r"except\s*:\s*pass"), "Bare except pass suppresses critical security exceptions!"),
        (re.compile(r"subprocess\.run\(.*shell\s*=\s*True.*\)"), "Insecure shell=True command execution detected!"),
    ]

    @classmethod
    def audit_source_string(cls, code: str) -> Dict[str, any]:
        violations: List[str] = []

        # 1. Regex pattern scan
        for pattern, warning in cls.FORBIDDEN_PATTERNS:
            if pattern.search(code):
                violations.append(warning)

        # 2. AST parsing for structural integrity
        syntax_valid = False
        try:
            tree = ast.parse(code)
            syntax_valid = True
            
            # Check for missing docstrings on top-level functions
            for node in tree.body:
                if isinstance(node, ast.FunctionDef):
                    if not ast.get_docstring(node):
                        violations.append(f"Function '{node.name}' lacks docstring documentation.")
        except SyntaxError as e:
            violations.append(f"Syntax error in generated code: {e}")

        passed = len(violations) == 0 and syntax_valid

        return {
            "syntax_valid": syntax_valid,
            "violations_count": len(violations),
            "violations": violations,
            "passed_quality_gate": passed,
            "verdict": "VERIFIED_SAFE_TO_MERGE" if passed else "REVISE_AI_OUTPUT"
        }
